version: "2.1"

services:
  traefik:
    image: "traefik:1.5"
    command: "--debug --docker --docker.watch=true --docker.exposedbydefault=false --web"
    networks:
      - main
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  main:
    external: true
